package com.eischet.janitor.version;

/**
 * The project's revision, baked in at build time from the {@code revision} property declared
 * once in the root pom.xml. Generated by templating-maven-plugin -- see janitor-lang/pom.xml --
 * so there is exactly one place ({@code pom.xml}) where the revision is maintained.
 */
public final class Revision {

    public static final String REVISION = "${revision}";

    private Revision() {
    }

}
