// SPDX-FileCopyrightText: 2021-2026 Eischet Software e.K.
// SPDX-License-Identifier: MIT

package com.eischet.dbxs.dialects;

import com.eischet.dbxs.SimplePreparedStatement;
import com.eischet.dbxs.metadata.DatabaseVersion;
import com.eischet.dbxs.metadata.SqlTypeInterpreter;
import com.eischet.dbxs.statements.SelectStatement;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.sql.Clob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/** Encapsulates the differences between database products, e.g. how identifiers are quoted and how queries are limited. */
public interface DatabaseDialect {

    /**
     * Quotes a column name if the database needs that, e.g. because it is a reserved word.
     * @param columnName the column name
     * @return the quoted column name
     */
    default @NotNull String quoteColumn(@NotNull String columnName) {
        return columnName;
    }

    /**
     * Quotes a table name if the database needs that.
     * @param tableName the table name
     * @return the quoted table name
     */
    default @NotNull String quoteTableName(@NotNull String tableName) {
        return quoteTableName(null, tableName);
    }

    /**
     * Quotes a table name if the database needs that, and prefixes it with the schema.
     * @param schema the schema, may be null
     * @param tableName the table name
     * @return the qualified table name
     */
    default @NotNull String quoteTableName(@Nullable String schema, @NotNull String tableName) {
        if (schema == null || schema.isEmpty()) {
            return tableName;
        } else {
            return schema + "." + tableName;
        }
    }

    /**
     * Escape character used in LIKE patterns built via {@link #likeCondition} and {@link #escapeLikePattern}.
     */
    char LIKE_ESCAPE = '\\';

    /**
     * Escapes the LIKE wildcards in a user-supplied search value, so that it is matched literally.
     * The result is meant to be used with the {@code escape} clause generated by {@link #likeCondition}.
     */
    default @NotNull String escapeLikePattern(@NotNull String value) {
        final StringBuilder out = new StringBuilder(value.length() + 4);
        for (int i = 0; i < value.length(); i++) {
            final char c = value.charAt(i);
            if (c == LIKE_ESCAPE || c == '%' || c == '_' || isAdditionalLikeWildcard(c)) {
                out.append(LIKE_ESCAPE);
            }
            out.append(c);
        }
        return out.toString();
    }

    /**
     * Dialect-specific wildcard characters besides '%' and '_' (e.g. '[' on MS SQL Server).
     */
    default boolean isAdditionalLikeWildcard(char c) {
        return false;
    }

    /**
     * Builds a "column LIKE ?" condition with a single placeholder for a pattern that was escaped with
     * {@link #escapeLikePattern}.
     *
     * @param quotedColumn the column, already quoted
     * @param negate       generate NOT LIKE
     * @param ignoreCase   compare case-insensitively; dialects whose default comparison is already case-insensitive may ignore this
     */
    default @NotNull String likeCondition(@NotNull String quotedColumn, boolean negate, boolean ignoreCase) {
        final String op = negate ? " not like " : " like ";
        final String escape = " escape '" + LIKE_ESCAPE + "'";
        if (ignoreCase) {
            return foldCase(quotedColumn) + op + foldCase("?") + escape;
        }
        return quotedColumn + op + "?" + escape;
    }

    /**
     * Wraps an SQL expression so that comparisons on it ignore case. Dialects whose comparisons already ignore
     * case (MS SQL Server with a case-insensitive collation) return the expression unchanged.
     */
    default @NotNull String foldCase(@NotNull String expression) {
        return "lower(" + expression + ")";
    }

    /**
     * Condition that is true for NULL and empty strings. Oracle stores '' as NULL, so it overrides this.
     */
    default @NotNull String isEmptyCondition(@NotNull String quotedColumn) {
        return "(" + quotedColumn + " is null or " + quotedColumn + " = '')";
    }

    /**
     * Counterpart of {@link #isEmptyCondition}.
     */
    default @NotNull String isNotEmptyCondition(@NotNull String quotedColumn) {
        return "(" + quotedColumn + " is not null and " + quotedColumn + " != '')";
    }

    /**
     * @return true if the database requires an ORDER BY clause to use limit and offset
     */
    boolean limitAndOffsetRequiresOrderBy();
    /**
     * Checks whether the database supports limiting the number of rows in a query.
     * @param databaseVersion the version of the database
     * @return true if limit and offset are supported
     */
    boolean canLimitAndOffset(final DatabaseVersion databaseVersion);

    @NotNull SelectStatement addLimitAndOffset(@NotNull SelectStatement selectStatement);
    @NotNull SimplePreparedStatement addLimitAndOffset(@NotNull SimplePreparedStatement statement, int limit, int offset) throws SQLException;

    /**
     * Returns a statement that fetches the next value from the given sequence.
     *
     * Not all databases <b>have</b> sequences, but that is not a problem, because this function is only used
     * internally and is not exposed to end users. It is therefore only ever run against supported databases,
     * which currently are PostgreSQL, Oracle and MS SQL, and all of them have sequences.
     *
     * @param schema optionales Schema
     * @param seq the name of the sequence
     * @return a query for the next value of the sequence, or null if the database does not support sequences
     */
    @Nullable
    SelectStatement getNextValueQuery(@Nullable String schema, @NotNull String seq);

    /**
     * Returns a statement that fetches the next value from a sequence of the default schema.
     * @param sequence the name of the sequence
     * @return a query for the next value, or null if the database does not support sequences
     */
    @Nullable
    default SelectStatement getNextValueQuery(@NotNull String sequence) {
        return getNextValueQuery(null, sequence);
    }

    /**
     * Returns a statement that fetches the current value of a sequence.
     * @param schema the schema, may be null
     * @param seq the name of the sequence
     * @return a query for the current value, or null if the database does not support sequences
     */
    @Nullable
    SelectStatement getCurrentValueQuery(@Nullable String schema, @NotNull String seq);

    /**
     * Binds a long text to a parameter of a prepared statement.
     * @param ps the statement
     * @param i the index of the parameter
     * @param clob the text
     * @throws SQLException if the value cannot be set
     */
    default void addClobToStatement(@NotNull PreparedStatement ps, int i, StringReader clob) throws SQLException {
        ps.setClob(i, clob);
    }

    /**
     * Reads a long text in a national character set from a column.
     * @param rs the result set
     * @param col the index of the column
     * @return the text, or null if the column is NULL
     * @throws SQLException on database errors
     */
    default @Nullable String readNationalClob(@NotNull ResultSet rs, int col) throws SQLException {
        final Clob clob = rs.getClob(col);
        if (clob == null) {
            return null;
        }
        try (final @Nullable Reader reader = clob.getCharacterStream()) {
            if (reader == null) {
                return null;
            }
            return SqlTypeInterpreter.transferToString(reader);
        } catch (IOException e) {
            throw new SQLException(e);
        }

    }

    /**
     * Reads a long text from a column.
     * @param rs the result set
     * @param col the index of the column
     * @return the text, or null if the column is NULL
     * @throws SQLException on database errors
     */
    default @Nullable String readRegularClob(@NotNull ResultSet rs, int col) throws SQLException {
        final Clob clob = rs.getClob(col);
        if (clob == null) {
            return null;
        }
        try (final @Nullable Reader reader = clob.getCharacterStream()) {
            if (reader == null) {
                return null;
            }
            return SqlTypeInterpreter.transferToString(reader);
        } catch (IOException e) {
            throw new SQLException(e);
        }

    }

    /**
     * @return true if binary data has to be bound with {@code setBytes}, e.g. for LONG RAW columns
     */
    default boolean isLegacySetBytesRequired() {
        return false;
    }
}
