/*
 * © Eischet Software e.K., Köln
 */

package com.eischet.dbxs.dialects;

import com.eischet.dbxs.SimplePreparedStatement;
import com.eischet.dbxs.metadata.DatabaseVersion;
import com.eischet.dbxs.metadata.SqlTypeInterpreter;
import com.eischet.dbxs.statements.SelectStatement;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.sql.Clob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public interface DatabaseDialect {

    default @NotNull String quoteColumn(@NotNull String columnName) {
        return columnName;
    }

    default @NotNull String quoteTableName(@NotNull String tableName) {
        return quoteTableName(null, tableName);
    }

    default @NotNull String quoteTableName(@Nullable String schema, @NotNull String tableName) {
        if (schema == null || schema.isEmpty()) {
            return tableName;
        } else {
            return schema + "." + tableName;
        }
    }

    /**
     * Escape character used in LIKE patterns built via {@link #likeCondition} and {@link #escapeLikePattern}.
     */
    char LIKE_ESCAPE = '\\';

    /**
     * Escapes the LIKE wildcards in a user-supplied search value, so that it is matched literally.
     * The result is meant to be used with the {@code escape} clause generated by {@link #likeCondition}.
     */
    default @NotNull String escapeLikePattern(@NotNull String value) {
        final StringBuilder out = new StringBuilder(value.length() + 4);
        for (int i = 0; i < value.length(); i++) {
            final char c = value.charAt(i);
            if (c == LIKE_ESCAPE || c == '%' || c == '_' || isAdditionalLikeWildcard(c)) {
                out.append(LIKE_ESCAPE);
            }
            out.append(c);
        }
        return out.toString();
    }

    /**
     * Dialect-specific wildcard characters besides '%' and '_' (e.g. '[' on MS SQL Server).
     */
    default boolean isAdditionalLikeWildcard(char c) {
        return false;
    }

    /**
     * Builds a "column LIKE ?" condition with a single placeholder for a pattern that was escaped with
     * {@link #escapeLikePattern}.
     *
     * @param quotedColumn the column, already quoted
     * @param negate       generate NOT LIKE
     * @param ignoreCase   compare case-insensitively; dialects whose default comparison is already case-insensitive may ignore this
     */
    default @NotNull String likeCondition(@NotNull String quotedColumn, boolean negate, boolean ignoreCase) {
        final String op = negate ? " not like " : " like ";
        final String escape = " escape '" + LIKE_ESCAPE + "'";
        if (ignoreCase) {
            return foldCase(quotedColumn) + op + foldCase("?") + escape;
        }
        return quotedColumn + op + "?" + escape;
    }

    /**
     * Wraps an SQL expression so that comparisons on it ignore case. Dialects whose comparisons already ignore
     * case (MS SQL Server with a case-insensitive collation) return the expression unchanged.
     */
    default @NotNull String foldCase(@NotNull String expression) {
        return "lower(" + expression + ")";
    }

    /**
     * Condition that is true for NULL and empty strings. Oracle stores '' as NULL, so it overrides this.
     */
    default @NotNull String isEmptyCondition(@NotNull String quotedColumn) {
        return "(" + quotedColumn + " is null or " + quotedColumn + " = '')";
    }

    /**
     * Counterpart of {@link #isEmptyCondition}.
     */
    default @NotNull String isNotEmptyCondition(@NotNull String quotedColumn) {
        return "(" + quotedColumn + " is not null and " + quotedColumn + " != '')";
    }

    boolean limitAndOffsetRequiresOrderBy();
    boolean canLimitAndOffset(final DatabaseVersion databaseVersion);

    @NotNull SelectStatement addLimitAndOffset(@NotNull SelectStatement selectStatement);
    @NotNull SimplePreparedStatement addLimitAndOffset(@NotNull SimplePreparedStatement statement, int limit, int offset) throws SQLException;

    /**
     * Gibt ein Statement zurück, das den nächsten Wert aus der angegebenen Sequence holt.
     *
     * Nicht alle Datenbanken <b>haben</b> Sequences, aber das ist nicht schlimm, weil diese Funktion nur intern
     * genutzt wird und nicht für Kunden zugänglich ist. Darum kann sie nur gegen unterstützte Datenbanken
     * ausgeführt werden, das sind aktuell PostgreSQL, Oracle und MS SQL, und die haben allesamt Sequences.
     *
     * @param schema optionales Schema
     * @param seq Name der Sequence
     * @return eine Abfrage für den nächsten Wert der Sequence, oder null wenn die Datenbank keine Sequences kennt
     */
    @Nullable
    SelectStatement getNextValueQuery(@Nullable String schema, @NotNull String seq);

    @Nullable
    default SelectStatement getNextValueQuery(@NotNull String sequence) {
        return getNextValueQuery(null, sequence);
    }

    @Nullable
    SelectStatement getCurrentValueQuery(@Nullable String schema, @NotNull String seq);

    default void addClobToStatement(@NotNull PreparedStatement ps, int i, StringReader clob) throws SQLException {
        ps.setClob(i, clob);
    }

    default @Nullable String readNationalClob(@NotNull ResultSet rs, int col) throws SQLException {
        final Clob clob = rs.getClob(col);
        if (clob == null) {
            return null;
        }
        try (final @Nullable Reader reader = clob.getCharacterStream()) {
            if (reader == null) {
                return null;
            }
            return SqlTypeInterpreter.transferToString(reader);
        } catch (IOException e) {
            throw new SQLException(e);
        }

    }

    default @Nullable String readRegularClob(@NotNull ResultSet rs, int col) throws SQLException {
        final Clob clob = rs.getClob(col);
        if (clob == null) {
            return null;
        }
        try (final @Nullable Reader reader = clob.getCharacterStream()) {
            if (reader == null) {
                return null;
            }
            return SqlTypeInterpreter.transferToString(reader);
        } catch (IOException e) {
            throw new SQLException(e);
        }

    }

    default boolean isLegacySetBytesRequired() {
        return false;
    }
}
