// SPDX-FileCopyrightText: 2021-2026 Eischet Software e.K.
// SPDX-License-Identifier: MIT

/**
 * This package contains code generated by the ANTLR parser generator.
 */
package com.eischet.janitor.lang;